"""rename addressee_id to receiver_id in friendships table

Revision ID: 9d0e5443047e
Revises: b293026a2667
Create Date: 2026-01-27 07:17:56.369119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d0e5443047e'
down_revision = 'b293026a2667'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 컬럼 이름 변경 (데이터 유지)
    op.alter_column('friendships', 'addressee_id',
                    new_column_name='receiver_id',
                    existing_type=sa.Integer(),
                    nullable=False)
    # 인덱스 재생성
    op.drop_index('ix_friendships_addressee_id', table_name='friendships')
    op.create_index(op.f('ix_friendships_receiver_id'), 'friendships', ['receiver_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 컬럼 이름 복원 (데이터 유지)
    op.alter_column('friendships', 'receiver_id',
                    new_column_name='addressee_id',
                    existing_type=sa.Integer(),
                    nullable=False)
    # 인덱스 복원
    op.drop_index(op.f('ix_friendships_receiver_id'), table_name='friendships')
    op.create_index('ix_friendships_addressee_id', 'friendships', ['addressee_id'], unique=False)
    # ### end Alembic commands ###
