"""Add unique constraint to friendships table

Revision ID: afd5d050d260
Revises: 7974a0858fbe
Create Date: 2026-01-30 08:57:40.180461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd5d050d260'
down_revision = '7974a0858fbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_friendship_pair', 'friendships', ['requester_id', 'receiver_id'])
    op.create_check_constraint('ck_no_self_friend', 'friendships', 'requester_id != receiver_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_no_self_friend', 'friendships', type_='check')
    op.drop_constraint('uq_friendship_pair', 'friendships', type_='unique')
    # ### end Alembic commands ###
