"""add foreign key to monthly_scores user_id

Revision ID: 0ceb423c2879
Revises: 45f71363a042
Create Date: 2026-02-09 12:13:29.702876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ceb423c2879'
down_revision = '45f71363a042'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'monthly_scores', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'monthly_scores', type_='foreignkey')
    # ### end Alembic commands ###
