"""drop_scores_table

Revision ID: 20e256d6d379
Revises: e529d64d1a07
Create Date: 2026-02-16 12:25:54.898473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20e256d6d379'
down_revision = 'e529d64d1a07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scores_created_at', table_name='scores')
    op.drop_index('ix_scores_id', table_name='scores')
    op.drop_index('ix_scores_score', table_name='scores')
    op.drop_index('ix_scores_user_id', table_name='scores')
    op.drop_table('scores')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='scores_pkey')
    )
    op.create_index('ix_scores_user_id', 'scores', ['user_id'], unique=False)
    op.create_index('ix_scores_score', 'scores', ['score'], unique=False)
    op.create_index('ix_scores_id', 'scores', ['id'], unique=False)
    op.create_index('ix_scores_created_at', 'scores', ['created_at'], unique=False)
    # ### end Alembic commands ###
