"""Add foreign key to high_scores.user_id

Revision ID: 45f71363a042
Revises: f38f15d3477d
Create Date: 2026-02-09 11:43:19.782825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f71363a042'
down_revision = 'f38f15d3477d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'high_scores', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'high_scores', type_='foreignkey')
    # ### end Alembic commands ###
