"""add notices table

Revision ID: 77047707274c
Revises: 4500d95a9077
Create Date: 2026-04-04 04:06:08.632530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77047707274c'
down_revision = '4500d95a9077'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
