"""add monthly_scores table

Revision ID: 7974a0858fbe
Revises: 9d0e5443047e
Create Date: 2026-01-30 03:02:41.807561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7974a0858fbe'
down_revision = '9d0e5443047e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
