"""add_foreign_key_to_game_visits_user_id

Revision ID: 7c93967e31b7
Revises: 0ceb423c2879
Create Date: 2026-02-13 01:46:16.157939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c93967e31b7'
down_revision = '0ceb423c2879'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # users 테이블에 존재하지 않는 고아 user_id를 NULL로 정리
    op.execute(
        "UPDATE game_visits SET user_id = NULL "
        "WHERE user_id IS NOT NULL "
        "AND user_id NOT IN (SELECT id FROM users)"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'game_visits', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_visits', type_='foreignkey')
    # ### end Alembic commands ###
