"""add acl_entries table

Revision ID: e389a7b38f3d
Revises: 77047707274c
Create Date: 2026-05-23 11:36:30.956220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e389a7b38f3d'
down_revision = '77047707274c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notice_acl_entries_actor_id', table_name='notice_acl_entries')
    op.drop_index('ix_notice_acl_entries_id', table_name='notice_acl_entries')
    op.drop_index('ix_notice_acl_entries_resource_id', table_name='notice_acl_entries')
    op.drop_table('notice_acl_entries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notice_acl_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.CheckConstraint("permission::text = ANY (ARRAY['read'::character varying, 'manage'::character varying]::text[])", name='ck_notice_acl_permission'),
    sa.ForeignKeyConstraint(['resource_id'], ['notices.id'], name='notice_acl_entries_resource_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='notice_acl_entries_pkey'),
    sa.UniqueConstraint('actor_id', 'resource_id', 'permission', name='uq_notice_acl')
    )
    op.create_index('ix_notice_acl_entries_resource_id', 'notice_acl_entries', ['resource_id'], unique=False)
    op.create_index('ix_notice_acl_entries_id', 'notice_acl_entries', ['id'], unique=False)
    op.create_index('ix_notice_acl_entries_actor_id', 'notice_acl_entries', ['actor_id'], unique=False)
    # ### end Alembic commands ###
