"""drop high_scores table

Revision ID: e529d64d1a07
Revises: 60a77f2baf38
Create Date: 2026-02-16 10:38:13.614404

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e529d64d1a07'
down_revision = '60a77f2baf38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_high_scores_created_at', table_name='high_scores')
    op.drop_index('ix_high_scores_id', table_name='high_scores')
    op.drop_index('ix_high_scores_score', table_name='high_scores')
    op.drop_index('ix_high_scores_user_id', table_name='high_scores')
    op.drop_table('high_scores')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('high_scores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='high_scores_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='high_scores_pkey')
    )
    op.create_index('ix_high_scores_user_id', 'high_scores', ['user_id'], unique=True)
    op.create_index('ix_high_scores_score', 'high_scores', ['score'], unique=False)
    op.create_index('ix_high_scores_id', 'high_scores', ['id'], unique=False)
    op.create_index('ix_high_scores_created_at', 'high_scores', ['created_at'], unique=False)
    # ### end Alembic commands ###
