"""Add foreign key constraints to friendships table

Revision ID: f38f15d3477d
Revises: 6fe36d8bc6a2
Create Date: 2026-02-05 10:13:44.680519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f38f15d3477d'
down_revision = '6fe36d8bc6a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'friendships', 'users', ['requester_id'], ['id'])
    op.create_foreign_key(None, 'friendships', 'users', ['receiver_id'], ['id'])
    op.alter_column('users', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    # ### end Alembic commands ###
