"""Add nickname to monthly_scores

Revision ID: e9059978e80e
Revises: afd5d050d260
Create Date: 2026-02-04 07:33:55.392120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9059978e80e'
down_revision = 'afd5d050d260'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthly_scores', sa.Column('nickname', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthly_scores', 'nickname')
    # ### end Alembic commands ###
